language: c

matrix:
  include:
  - os: linux
    dist: trusty
    sudo: required

script:
- sudo apt-get install tree
- "./setup.sh"
- "./build.sh -a"
- mkdir ${TRAVIS_BUILD_NUMBER}
- cp *.tar.gz ${TRAVIS_BUILD_NUMBER}
- tree .

deploy:
  provider: s3
  access_key_id: "${AWS_ID}"
  secret_access_key: "${AWS_SECRET}"
  bucket: "opensource.nextthing.co"
  skip_cleanup: true
  acl: public_read
  region: us-west-2
  local-dir: ${TRAVIS_BUILD_NUMBER}
  upload-dir: artifacts-travis/armhf-debootstrap
