language: c

matrix:
  include:
  - os: linux
    dist: trusty
    sudo: required

script:
  - "./setup.sh"
  - "./build.sh -a"
  - mkdir -p upload/${TRAVIS_BUILD_NUMBER}
  - ls
  - cp rootfs.tar.gz upload/${TRAVIS_BUILD_NUMBER}/
  - "./build.sh -i"
  - ls
  - cp i386.rootfs.tar.gz upload/${TRAVIS_BUILD_NUMBER}

deploy:
  on:
    branch: chip/stable
  provider: s3
  access_key_id: "${AWS_ID}"
  secret_access_key: "${AWS_SECRET}"
  bucket: "opensource.nextthing.co"
  skip_cleanup: true
  acl: public_read
  region: us-west-2
  local-dir: upload
  upload-dir: artifacts-travis/armhf-debootstrap
